### ISSUE TITLE
How do I post a new idea to the ideas list?

### ISSUE THREAD

**Issue by aforaditya** [jitsi/gsoc-ideas#15]
Hello there,
I have a new feature idea in my mind but am not sure how can I post it to the ideas list of GSOC 2022 . Should I directly initiate a pull request for that or should I simply post it here in the Issue section? Your guidance would be of great help.

**Comment by dikshashukla455** [comment]
I think you should make a pull request for that idea as it is a direct way to add your idea to the ideas list instead of creating an issue.

**Comment by bgrozev** [comment]
Sure, go ahead and create a PR, or just share it here.
