### ISSUE TITLE
GSOC -22, Speech to Text (ISSUE) 

### ISSUE THREAD

**Issue by shivamsingh124** [jitsi/gsoc-ideas#20]
Hi ***Jitsi*** team,
I have used Artyom Speech to text API in past which can be very well integrated in this project, I am attaching a video demo of the working prototype as well.

## Why I am using artyom
* It's completely free
* It's accuracy is above the one present in the free model.
* It processes the data and even rectifies any pronunciation errors with its ML model.
* It converts the speech to text in real-time providing the user a lag-free & low latency experience.

## Working prototype:-
https://drive.google.com/file/d/15lmaRUiFTYdGFd-yCguBwRnsAr0I9J2d/view?usp=sharing

**Comment by shivamsingh124** [comment]
Link to issue :- https://github.com/jitsi/gsoc-ideas/blob/master/2022/speech-to-text.md

**Comment by nikvaessen** [comment]
Applications for GSoC should be made via the program website. Also Artyom.js seems to be a javascript wrapper around the browser's `webkitSpeechRecognition` API. Note that this is not 'free' [1] as in libri software [2]:

````
On some browsers, like Chrome, using Speech Recognition on a web page involves a server-based recognition engine. Your audio is sent to a web service for recognition processing, so it won't work offline.
````

[1] = https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition
[2] = https://www.gnu.org/philosophy/free-sw.en.html

**Comment by shivamsingh124** [comment]
@nikvaessen Got it!. So I should find an alternate that can work on offline mode also?

**Comment by nikvaessen** [comment]
No, it does not need to work offline, we want a _free_ solution. See the project description:

| The current speech-to-text implementation uses the paid, proprietary Google speech-to-text API. It would be nice to offer a free, privacy-friendly alternative.

**Comment by shivamsingh124** [comment]
@nikvaessen  Got it, I thought of working on our own ML model but it is not the case, I will look for a free alternative and will let you know at the earliest
