### ISSUE TITLE
Had new idea that I think is worth sharing

### ISSUE THREAD

**Issue by Henokaa** [jitsi/gsoc-ideas#22]
# Jitsi
Hi there, I just wanted to brainstorm a few things that I think is overlooked by many companies such as google meets, and I think this should be one of the many features that makes jitsi, special.

* If this idea doesn't make sense, please feel free to ignore it. 
# The idea
The idea is you know how there are pointers you can use while presenting your screen in google meets, but can participants show you any part of the screen they want to direct your attention to? they will have to spell it out to you every time they want to point out at something, and this is very challenging, especially in a coding presentation scenario. as a result, we can come up with a solution where the participant will be given an access by the presenter to use pointers from their end.<br />

<br />
I am not really sure if it is a good idea, so please let me know what you think 😊. and I will explain more.
<br />

**Comment by The-Shivam-garg** [comment]
I think that's really good one , Jitsi can make a difference in the market by coming up with this feature
