### ISSUE TITLE
Speech to text feature in GSoC 2022

### ISSUE THREAD

**Issue by sh-soltanpour** [jitsi/gsoc-ideas#25]
Hi everyone,
Hope you’re all doing great!

My name is Shahryar Soltanpour, I’m studying MSc in computer science at the University of Calgary. I’m very excited to join the Jitsi community. I want to contribute to [speech-to-text](https://github.com/jitsi/gsoc-ideas/blob/master/2022/speech-to-text.md) feature of Jigasi and I’m preparing my proposal for it. I would be more than happy to hear any advice from you about getting started or any features and ideas that you want me to include in my proposal.

Thanks in advance

**Comment by saghul** [comment]
Care to chime in @nikvaessen ?

**Comment by nikvaessen** [comment]
Hi Shahryar,

You could look into open-source solutions which provide near-real time transcription (in English).

**Comment by sh-soltanpour** [comment]
Hi @nikvaessen, 
Okay sure. Thanks for your response.
Besides, do you have anything in your mind to do as the qualification task?

**Comment by reetikaagajula** [comment]
Hello,
I have been looking into the project Speech to text feature in jitsi, I would like to send a proposal for this project so,I would like to know what are the requirements that are needed for the proposal.
Thank you

**Comment by saghul** [comment]
Ping @nikvaessen :-)

**Comment by reetikaagajula** [comment]
Hello @nikvaessen ,
I would want to know what are the requirements for the proposal in the project speech to text conversion .
Thank you.

**Comment by nikvaessen** [comment]
https://google.github.io/gsocguides/ has some guides for structuring a proposal. For this specific project, it would also be good to show that you have run a open source speech-to-text model on some audio you recorded yourself, and did some research on potential models we could use.

**Comment by reetikaagajula** [comment]
Hey @nikvaessen ,
Is there any possibility for you to review the proposals and suggest some changes before we submit the proposal in the gsoc site?
