### ISSUE TITLE
Multiple Recording Storage Providers - GSoC 

### ISSUE THREAD

**Issue by jayanth151002** [jitsi/gsoc-ideas#26]
Hello everyone! This is Jayanth, a second year undergraduate from Indian Institute of Technology, Madras. I am a software developer with strong expertise in web development (Javascript based). I was exploring all the projects put up for this year’s GSoC program and the ‘Multiple Recording Storage Providers’ project by Jitsi grabbed my interest. So, I would like to know about the potential mentors and what are their plans for this project. Any kind of inputs from them would help me draft the proposal. I wish to make an impactful contribution for this project. Is anyone planning for contributing to this project? I'm open for discussion.

**Comment by jayanth151002** [comment]
Thanks for your insightful answer @mihhu ! I'm super excited to work on this project. I have a question. Should all the meeting participants be able to choose the storage facility, or just the meeting moderator/host and then share it with participants? I have an outline for both the methods. I will look onto ways to implement this feature on mobile apps as well.

**Comment by mihhu** [comment]
> Thanks for your insightful answer @mihhu ! I'm super excited to work on this project. I have a question. Should all the meeting participants be able to choose the storage facility, or just the meeting moderator/host and then share it with participants? I have an outline for both the methods. I will look onto ways to implement this feature on mobile apps as well.

All the authenticated participants (with a valid JWT) should be able to choose a storage facility, log into it and start a recording that will be saved only in their respective storage account.

**Comment by jayanth151002** [comment]
> 

Ah right! Got it.

**Comment by jayanth151002** [comment]
> @jayanth151002 Sorry, I've updated my answer, I hope you didn't get too far into your proposal on the wrong path.
> 
> Thanks @damencho for pointing it out!

No worries! Thanks.

**Comment by mihhu** [comment]
I would like to give a helping hand mentoring 😃 

Kotlin and Java are used, but I don't think there will be any major changes needed there (unless you choose to push this feature in that direction, of course).

There's also a [bash section](https://github.com/jitsi/jitsi-upload-integrations/blob/56245f250ce5604699a343448e505138ba18e043/jitsi_uploader.sh#L56), but you won't be alone in this, so worry not! As for the front-end side, javascript and typescript are needed, and if you're not familiar with react, the ramp up is pretty quick, so this is no cause for worry either.
