### ISSUE TITLE
Speech to Text Feature.

### ISSUE THREAD

**Issue by SaachiKaup** [jitsi/gsoc-ideas#27]
Hello @saghul @nikvaessen!

Recently came across Jitsi while researching GSOC projects. Love the platform! Wanted to contribute to the real time speech to text feature. The options considered:

- [DeepSpeech2](https://github.com/PaddlePaddle/PaddleSpeech)
- [Facebooks Hubert](https://huggingface.co/facebook/hubert-large-ls960-ft) -with no LM, still got a fast, quality output)
- Improvements to Vosk.

But, to narrow these options down for you, knowing about what specific areas need improvement would be helpful. 

Regards!

**Comment by samiali12** [comment]
Hi!
Hope you are all doing well! I am Sami Ali. I am a sophomore undergraduate student majoring in computer science. I came across your project and found it very interesting. I am particularly interested in real-time "Speach-To-Text". I would love to know more about the project. should I ask my question here or better if I talked about the project with respective mentor.

**Comment by saghul** [comment]
Ping @nikvaessen :-)

**Comment by SaachiKaup** [comment]
Thank you for responding @saghul!

**Comment by nikvaessen** [comment]
I think some improvements can be made on:

1) make it easier to self-host with transcription enabled (by having it included in https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual/)
2) make the self-hosting viable, e.g. the results are decent on English, and can scale based on improvements in the field.

**Comment by SaachiKaup** [comment]
Thank you for responding @nikvaessen. Appreciate it :) This helps a lot!
