### ISSUE TITLE
ML audio enhancements project in GSoC' 2022 (Thread)

### ISSUE THREAD

**Issue by Spnetic-5** [jitsi/gsoc-ideas#28]
Hello @saghul  & @hristoterezov, I'm Saurabh pursuing a prefinal year Btech in India, I have good experience with ML & Development. I'm interested in applying at GSoC for ML audio enhancements project. I have started exploring the structure and flow of the Jitsi codebase. I would like to have your suggestions before starting with my proposal for this project.

Thanks

**Comment by saghul** [comment]
Thanks for getting in touch! Do you have any specific questions?

**Comment by Spnetic-5** [comment]
@saghul Apologies for the late reply🙇️ , Before I start writing my proposal, I'd like to get some comments from you. Could you kindly provide me with some more details on the audio enhancements project's expected outcomes?

**Comment by saghul** [comment]
They are listed here: https://github.com/jitsi/gsoc-ideas/blob/master/2022/ml-audio-enhancemants.md#expected-outcomes as an example, a police car / ambulance siren sound should be removed.

**Comment by Spnetic-5** [comment]
Okay thanks, I'll share my draft proposal soon!

**Comment by Spnetic-5** [comment]
Hello @saghul @hristoterezov,
Here is the link to my draft proposal: https://docs.google.com/document/d/1UTN7iMm1WQsToLEsVNGThrIEBZKGBFgQSws-n9U3SlY/edit?usp=sharing
Please review whenever you get time!
