### ISSUE TITLE
Speech to Text 

### ISSUE THREAD

**Issue by Rishabhk06** [jitsi/gsoc-ideas#30]
Hey... I was just exploring Speech to Text project ideas for GSoC 2022 and came across this Javascript [Web Speech](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) API which offers Speech Recognition. It seems to be quite accurate and real-time but the privacy policy is not very clear. However, it somewhere states:
> Chrome currently [takes the audio and sends it to Google's servers](https://www.google.com/chrome/privacy/whitepaper.html#speech) to perform the transcription.

Just wanted to know what are your views over the same and if it suits your requirements. Plus, I also tested the [DeepSpeech](https://github.com/mozilla/DeepSpeech) open-source library over a local setup and the results are good enough for the English language but not very convincing for other regional languages. Do you consider it a probable solution? Looking forward to suggestions and feedback @nikvaessen 

Regards
Rishabh

**Comment by nikvaessen** [comment]
There are 2 issues with the Web Speech API:

1) we want a solution which can be completely self-hosted, no audio should be send to a third party.
2) the solution needs to run server-side, as implemented in Jigasi.
