### ISSUE TITLE
JITSI: Speech-to-text with publicly available deep learning models

### ISSUE THREAD

**Issue by brb1996** [jitsi/gsoc-ideas#33]
Hi @nikvaessen, this is Bhargav B R. I have submitted my proposal for the Jitsi: speech-to-text project. 

I have tested various open source publicly available speech-to-text models like **Mozilla’s DeepSpeech, Coqui STT, Facebook’s flashlight, SpeechBrain and Kaldi**, comparing the word error rate and inference speed of each and also included the speech transcription results obtained by running against sample audio using various models in my GSOC proposal. 

For enabling communication between Jigasi and the web server hosting the open source model, I have designed a sample client-server model based application considering both **WebSocket** framework and **Rest Service** architecture, exposing the open source speech-to-text model as a service for serving transcription results back to the client. 

I went through the existing Jigasi implementation of speech-to-text conversion. I am very much interested in contributing to this project, making it a completely self-hosted solution for speech transcription. Please review my proposal.
Thank you.

**Comment by Gairick52** [comment]
@brb1996 i am new to open source can you suggest me some beginner friendly issues
