### ISSUE TITLE
Setting up JVB 

### ISSUE THREAD

**Issue by sarthaksarthak9** [jitsi/gsoc-ideas#37]
@saghul I’m trying to set up Jitsi Videobridge (JVB) and I’m encountering some errors. Could you please take a look at them?

![Screenshot from 2024-03-19 09-08-59](https://github.com/jitsi/gsoc-ideas/assets/122533767/7c0d3268-a136-4d0d-a05d-cd38d29f0dd5)

**Comment by saghul** [comment]
Ping @bgrozev

**Comment by damencho** [comment]
https://community.jitsi.org/t/gsoc24-prometheus-scraping-and-grafana-dashboards/130567/5?u=damencho
